// web/src/components/Cover.tsx
import { useEffect, useState } from 'react'
import { cn } from '../lib/cn'
import { api } from '../lib/api'

interface Props {
  src:       string | null   // null → fallback ngay
  title:     string
  className?: string
  fontSize?: string          // tailwind text-* class for fallback letters
  // Cache-buster — when the upstream cover.jpg gets replaced (e.g. metadata
  // re-pull) the URL stays the same. Append ?v=updated_at so the browser
  // refetches without hitting full no-cache.
  version?:  string | null
}

// Resolve relative API URLs (e.g. "/files/<slug>/cover.jpg") against
// VITE_API_URL when running cross-origin from the API. Same-origin dev/prod
// hits the Vite proxy and the relative URL stays untouched.
function resolve(src: string, version?: string | null): string {
  const base = /^https?:\/\//i.test(src) ? src : `${api.base}${src}`
  if (!version) return base
  return base.includes('?') ? `${base}&v=${encodeURIComponent(version)}` : `${base}?v=${encodeURIComponent(version)}`
}

export function Cover({ src, title, className, fontSize = 'text-xl', version }: Props) {
  const [failed, setFailed] = useState(false)

  // Reset failure state when src changes — without this, switching projects
  // to one with a working cover still shows the fallback.
  useEffect(() => { setFailed(false) }, [src])

  const showImg = src && !failed
  return (
    <div className={cn('flex items-center justify-center overflow-hidden bg-zinc-100', className)}>
      {showImg ? (
        <img
          src={resolve(src, version)}
          alt={title}
          className="w-full h-full object-cover"
          loading="lazy"
          onError={() => setFailed(true)}
        />
      ) : (
        <span className={cn('font-black text-zinc-300 select-none', fontSize)}>
          {title.slice(0, 2).toUpperCase()}
        </span>
      )}
    </div>
  )
}

// web-svelte/src/lib/ui/Cover.svelte
<script lang="ts">
  import { cn } from '$lib/cn';
  import { useSourceFetch } from '$lib/sourceFetch.svelte';

  let {
    src = null,
    title,
    alt,
    class: cls = '',
    fontSize = 'text-xl',
    version,
    aspect,
  }: {
    src?: string | null;
    title?: string | null;
    alt?: string | null;
    class?: string;
    fontSize?: string;
    version?: string | null;
    aspect?: string;
  } = $props();

  const sf = useSourceFetch();
  let failed = $state(false);
  const safeTitle = $derived((title ?? alt ?? '').trim());
  const url = $derived(!failed ? coverUrl(src, version, sf.toBrowserUrl) : null);

  $effect(() => {
    src;
    failed = false;
  });

  function coverUrl(
    value: string | null | undefined,
    v: string | null | undefined,
    proxify: (url: string) => string,
  ): string | null {
    if (!value) return null;
    const isAbs = /^https?:\/\//i.test(value);
    const base = isAbs ? proxify(value) : value;
    if (!v) return base;
    return base.includes('?')
      ? `${base}&v=${encodeURIComponent(v)}`
      : `${base}?v=${encodeURIComponent(v)}`;
  }
</script>

<div class={cn('flex items-center justify-center overflow-hidden bg-surface-2', aspect, cls)}>
  {#if url}
    <img src={url} alt={safeTitle} class="w-full h-full object-cover" loading="lazy" onerror={() => { failed = true; }} />
  {:else}
    <span class={cn('font-black text-text-subtle/60 select-none', fontSize)}>
      {safeTitle.slice(0, 2).toUpperCase() || '—'}
    </span>
  {/if}
</div>
