// web/src/features/reader/components/ReaderSettingsSheet.tsx
// ReaderSettingsSheet — minimal layout.
//
//   CHẾ ĐỘ ĐỌC
//     [📖 Tiêu chuẩn] [📕 Phải→Trái] [⬇ Dọc] [📜 Webtoon]
//     ↑ segmented radio, h-14 cards (token: list row card)
//
//   HIỂN THỊ                (desktop only)
//     Bề rộng tối đa                       1040 px
//     ●─────────────
//
// Mobile = BottomSheet, desktop = Modal (sm).

import { type LucideIcon } from 'lucide-react'
import {
  RectangleVertical, BookOpen, ScrollText, ArrowDown,
} from 'lucide-react'

import { Modal } from '@shared/ui/Modal'
import { BottomSheet } from '@shared/ui/BottomSheet'
import { cn } from '@shared/lib/cn'
import { useIsDesktop } from '@shared/lib/useMediaQuery'
import {
  useReaderSettings, usePatchReaderSettings,
  PAGE_WIDTH_MIN, PAGE_WIDTH_MAX,
  type ReadingStyle,
} from '../settings'


interface Props {
  open:    boolean
  onClose: () => void
}


export function ReaderSettingsSheet({ open, onClose }: Props) {
  const isDesktop = useIsDesktop()

  if (isDesktop) {
    return (
      <Modal open={open} onClose={onClose} title="Cài đặt đọc" size="sm">
        <Body isDesktop />
      </Modal>
    )
  }
  return (
    <BottomSheet open={open} onClose={onClose} title="Cài đặt đọc">
      <Body isDesktop={false} />
    </BottomSheet>
  )
}


// ── Body ───────────────────────────────────────────────────────


const STYLE_OPTIONS: Array<{
  value: ReadingStyle
  label: string
  icon:  LucideIcon
}> = [
  { value: 'standard', label: 'Tiêu chuẩn', icon: RectangleVertical },
  { value: 'rtl',      label: 'Phải→Trái',  icon: BookOpen },
  { value: 'vertical', label: 'Dọc',         icon: ArrowDown },
  { value: 'webtoon',  label: 'Webtoon',     icon: ScrollText },
]


function Body({ isDesktop }: { isDesktop: boolean }) {
  const s     = useReaderSettings()
  const patch = usePatchReaderSettings()

  return (
    <div className="px-4 sm:px-5 py-4 space-y-6">
      <Section title="Chế độ đọc" hint="Áp dụng cho mọi truyện">
        <ModeSegmented
          value={s.style}
          onChange={(v) => patch({ style: v })}
        />
      </Section>

      {isDesktop && (
        <>
          <div className="border-t border-border-soft" />
          <Section title="Hiển thị">
            <div className="space-y-3">
              <div className="flex items-baseline justify-between gap-2">
                <span className="text-sm text-text">Bề rộng tối đa</span>
                <span className="text-xs tabular-nums text-text-muted h-6 px-2 inline-flex items-center rounded-full bg-surface-2">
                  {s.pageWidth} px
                </span>
              </div>
              <input
                type="range"
                min={PAGE_WIDTH_MIN}
                max={PAGE_WIDTH_MAX}
                step={20}
                value={s.pageWidth}
                onChange={(e) => patch({ pageWidth: Number(e.target.value) })}
                className="reader-slider w-full h-1 appearance-none rounded-full bg-surface-2 cursor-pointer accent-accent"
              />
            </div>
          </Section>
        </>
      )}
    </div>
  )
}


// ── Segmented mode picker ─────────────────────────────────────


function ModeSegmented({
  value, onChange,
}: {
  value:    ReadingStyle
  onChange: (v: ReadingStyle) => void
}) {
  return (
    <div
      role="radiogroup"
      aria-label="Chế độ đọc"
      className="grid grid-cols-2 sm:grid-cols-4 gap-2"
    >
      {STYLE_OPTIONS.map(opt => {
        const Icon = opt.icon
        const active = value === opt.value
        return (
          <button
            key={opt.value}
            type="button"
            role="radio"
            aria-checked={active}
            onClick={() => onChange(opt.value)}
            className={cn(
              'inline-flex flex-col items-center justify-center gap-2',
              'h-14 px-2 rounded-sm text-xs font-medium',
              'transition-colors duration-150 cursor-pointer',
              active
                ? 'bg-accent-bg text-accent-text'
                : 'bg-surface-2 text-text-muted hover:bg-hover hover:text-text',
            )}
          >
            <Icon size={18} className={active ? 'text-accent' : ''} />
            <span className="truncate w-full text-center leading-tight">
              {opt.label}
            </span>
          </button>
        )
      })}
    </div>
  )
}


// ── Section block ─────────────────────────────────────────────


function Section({
  title, hint, children,
}: {
  title:    string
  hint?:    string
  children: React.ReactNode
}) {
  return (
    <section className="space-y-3">
      <div className="flex items-baseline justify-between gap-2">
        <h3 className="text-xs uppercase tracking-wider text-text-subtle font-semibold">
          {title}
        </h3>
        {hint && (
          <span className="text-xs text-text-subtle">{hint}</span>
        )}
      </div>
      {children}
    </section>
  )
}

// web-svelte/src/lib/reader/ReaderSettingsSheet.svelte
<script lang="ts">
  import { Languages, ScrollText } from 'lucide-svelte';
  import { localSettings, READER_PAGE_WIDTH_MAX, READER_PAGE_WIDTH_MIN } from '$lib/localSettings.svelte';
  import ReaderDropdown from './ReaderDropdown.svelte';

  let { open, anchor, onClose }: { open: boolean; anchor: HTMLElement | null; onClose: () => void } = $props();

  function setPageWidth(value: number): void {
    localSettings.update({ reader_page_width: value });
  }
</script>

<ReaderDropdown {open} {anchor} {onClose} align="end" width="min(23rem, calc(100vw - 1rem))">
  <div class="px-4 py-3 border-b border-divider">
    <div class="text-sm font-semibold text-text">Cài đặt đọc</div>
    <div class="text-xs text-text-subtle">Tối ưu cho dịch overlay</div>
  </div>

  <div class="px-4 py-4 space-y-5 overflow-y-auto max-h-[min(70dvh,30rem)]">
    <section class="space-y-3">
      <div class="flex items-center gap-2 rounded-md bg-surface-2 px-3 py-3">
        <div class="grid size-9 shrink-0 place-items-center rounded-md bg-accent-bg text-accent">
          <ScrollText size={18} />
        </div>
        <div class="min-w-0">
          <div class="text-sm font-semibold text-text">Cuộn dọc tối ưu dịch thuật</div>
          <p class="mt-0.5 text-xs leading-relaxed text-text-muted">
            Reader dùng một luồng page-local duy nhất để overlay dịch, OCR và vị trí chữ bám đúng từng trang.
          </p>
        </div>
      </div>
    </section>

    <div class="border-t border-border-soft"></div>

    <section class="space-y-3">
      <div class="flex items-baseline justify-between gap-2">
        <h3 class="text-xs uppercase tracking-wider text-text-subtle font-semibold">Hiển thị</h3>
      </div>
      <div class="space-y-3">
        <div class="flex items-start gap-2 rounded-md border border-border-soft bg-surface px-3 py-2 text-xs text-text-muted">
          <Languages size={14} class="mt-0.5 shrink-0 text-accent" />
          <span>Dịch chạy theo vùng đang đọc trước, sau đó hoàn tất phần còn lại của chương.</span>
        </div>
        <div class="flex items-baseline justify-between gap-2">
          <span class="text-sm text-text">Bề rộng tối đa</span>
          <span class="text-xs tabular-nums text-text-muted h-6 px-2 inline-flex items-center rounded-full bg-surface-2">
            {localSettings.state.reader_page_width} px
          </span>
        </div>
        <input
          type="range"
          min={READER_PAGE_WIDTH_MIN}
          max={READER_PAGE_WIDTH_MAX}
          step="20"
          value={localSettings.state.reader_page_width}
          oninput={(event) => setPageWidth(Number(event.currentTarget.value))}
          class="reader-slider w-full h-1 appearance-none rounded-full bg-surface-2 cursor-pointer accent-accent"
        />
      </div>
    </section>
  </div>
</ReaderDropdown>
