// web-svelte/src/lib/ui/Cover.svelte
<script lang="ts">
  import { cn } from '$lib/cn';
  import { useSourceFetch } from '$lib/sourceFetch.svelte';

  let {
    src = null,
    title,
    alt,
    class: cls = '',
    fontSize = 'text-xl',
    version,
    aspect,
  }: {
    src?: string | null;
    title?: string | null;
    alt?: string | null;
    class?: string;
    fontSize?: string;
    version?: string | null;
    aspect?: string;
  } = $props();

  const sf = useSourceFetch();
  let failed = $state(false);
  const safeTitle = $derived((title ?? alt ?? '').trim());
  const url = $derived(!failed ? coverUrl(src, version, sf.toBrowserUrl) : null);

  $effect(() => {
    src;
    failed = false;
  });

  function coverUrl(
    value: string | null | undefined,
    v: string | null | undefined,
    proxify: (url: string) => string,
  ): string | null {
    if (!value) return null;
    const isAbs = /^https?:\/\//i.test(value);
    const base = isAbs ? proxify(value) : value;
    if (!v) return base;
    return base.includes('?')
      ? `${base}&v=${encodeURIComponent(v)}`
      : `${base}?v=${encodeURIComponent(v)}`;
  }
</script>

<div class={cn('flex items-center justify-center overflow-hidden bg-surface-2', aspect, cls)}>
  {#if url}
    <img src={url} alt={safeTitle} class="w-full h-full object-cover" loading="lazy" onerror={() => { failed = true; }} />
  {:else}
    <span class={cn('font-black text-text-subtle/60 select-none', fontSize)}>
      {safeTitle.slice(0, 2).toUpperCase() || '—'}
    </span>
  {/if}
</div>

// web/src/shared/ui/Cover.tsx
import { useEffect, useState } from 'react'
import { cn } from '@shared/lib/cn'
import { useSourceFetch } from '@features/browse/SourceFetchProvider'

const API_BASE = window.location.hostname.endsWith('.discordsays.com')
  ? ''
  : (import.meta.env.VITE_PUBLIC_BASE_URL ?? '')

// Resolve a cover URL — absolute upstream → CDN proxy,
// relative `/files/...` → API base.
export function coverUrl(
  src: string | null,
  version: string | null | undefined,
  proxify: (url: string) => string,
): string | null {
  if (!src) return null
  const isAbs = /^https?:\/\//i.test(src)
  const base  = isAbs ? proxify(src) : `${API_BASE}${src}`
  if (!version) return base
  return base.includes('?')
    ? `${base}&v=${encodeURIComponent(version)}`
    : `${base}?v=${encodeURIComponent(version)}`
}

interface Props {
  src:        string | null     // null → fallback ngay
  title:      string | null | undefined
  className?: string
  fontSize?:  string             // tailwind text-* class for fallback letters
  version?:   string | null
}

export function Cover({ src, title, className, fontSize = 'text-xl', version }: Props) {
  const [failed, setFailed] = useState(false)
  const { toBrowserUrl: proxify } = useSourceFetch()

  // Reset failure state when src changes — without this, switching projects
  // to one with a working cover still shows the fallback.
  useEffect(() => { setFailed(false) }, [src])

  const url = !failed ? coverUrl(src, version, proxify) : null
  const safeTitle = (title ?? '').trim()

  return (
    <div className={cn('flex items-center justify-center overflow-hidden bg-surface-2', className)}>
      {url ? (
        <img
          src={url}
          alt={safeTitle}
          className="w-full h-full object-cover"
          loading="lazy"
          onError={() => setFailed(true)}
        />
      ) : (
        <span className={cn('font-black text-text-subtle/60 select-none', fontSize)}>
          {safeTitle.slice(0, 2).toUpperCase() || '—'}
        </span>
      )}
    </div>
  )
}
