// web-svelte/src/routes/(app)/library/+page.svelte
<script lang="ts">
  import { Plus, Search } from 'lucide-svelte';
  import { listLibraryWorks } from '$lib/works/repo';
  import type { LibraryStatus, Work } from '$lib/db';
  import { cn } from '$lib/cn';
  import AddMangaModal from '$lib/library/AddMangaModal.svelte';
  import Button from '$lib/ui/Button.svelte';
  import EmptyState from '$lib/ui/EmptyState.svelte';
  import Spinner from '$lib/ui/Spinner.svelte';
  import WorkCard from '$lib/ui/WorkCard.svelte';

  type StatusFilter = 'all' | LibraryStatus;

  const statusTabs: Array<{ value: StatusFilter; label: string }> = [
    { value: 'all', label: 'Tất cả' },
    { value: 'reading', label: 'Đang đọc' },
    { value: 'plan', label: 'Định đọc' },
    { value: 'done', label: 'Đã đọc' },
    { value: 'dropped', label: 'Bỏ' },
  ];

  let works = $state<Work[]>([]);
  let status = $state<StatusFilter>('all');
  let query = $state('');
  let loading = $state(true);
  let error = $state('');
  let addOpen = $state(false);

  const counts = $derived({
    all: works.length,
    reading: works.filter((work) => work.library_status === 'reading').length,
    plan: works.filter((work) => work.library_status === 'plan').length,
    done: works.filter((work) => work.library_status === 'done').length,
    dropped: works.filter((work) => work.library_status === 'dropped').length,
  });
  const filtered = $derived(
    works.filter((work) => {
      if (status !== 'all' && work.library_status !== status) return false;
      const term = query.trim().toLowerCase();
      return !term || work.title.toLowerCase().includes(term);
    }),
  );

  $effect(() => {
    listLibraryWorks()
      .then((items) => { works = items; })
      .catch((err) => { error = err instanceof Error ? err.message : String(err); })
      .finally(() => { loading = false; });
  });
</script>

<svelte:head><title>Thư viện — Hội Mê Truyện</title></svelte:head>

{#if loading}
  <div class="flex justify-center py-16"><Spinner size={20} /></div>
{:else if error}
  <p class="text-error-text text-center py-20">{error}</p>
{:else if works.length === 0}
  <div class="max-w-3xl mx-auto px-4 sm:px-6 py-10">
    <EmptyState title="Thư viện trống" hint="Tìm truyện hoặc dán URL để thêm vào.">
      {#snippet action()}
        <Button variant="primary" size="md" onclick={() => { addOpen = true; }}>
          <Plus size={14} /> Thêm truyện
        </Button>
      {/snippet}
    </EmptyState>
  </div>
  <AddMangaModal open={addOpen} onClose={() => { addOpen = false; }} />
{:else}
  <div class="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-5">
    <header class="space-y-3">
      <div class="flex items-center justify-between gap-3">
        <div>
          <h1 class="text-lg font-semibold text-text">Thư viện</h1>
          <p class="text-xs text-text-muted">{works.length} truyện</p>
        </div>
        <div class="flex items-center gap-2">
          <Button variant="secondary" size="sm" onclick={() => { addOpen = true; }}>
            <Plus size={14} /> Thêm
          </Button>
          <a href="/explore" class="inline-flex items-center justify-center gap-1.5 h-7 px-2.5 rounded-sm bg-transparent text-text-muted hover:text-text hover:bg-hover text-xs font-medium transition-colors">
            Khám phá
          </a>
        </div>
      </div>

      <div class="flex flex-wrap gap-2">
        {#each statusTabs as tab (tab.value)}
          {@const active = status === tab.value}
          <button
            type="button"
            onclick={() => { status = tab.value; }}
            class={cn(
              'inline-flex items-center gap-1.5 h-7 px-3 rounded-full text-xs font-medium transition-colors',
              active ? 'bg-accent-bg text-accent-text' : 'bg-surface-2 text-text-muted hover:bg-hover hover:text-text',
            )}
          >
            {tab.label}
            <span class="tabular-nums text-[10px] opacity-80">{counts[tab.value]}</span>
          </button>
        {/each}
      </div>

      <div class="relative max-w-xl">
        <Search size={14} class="absolute left-2.5 top-1/2 -translate-y-1/2 text-text-subtle" />
        <input
          type="search"
          bind:value={query}
          placeholder="Tìm trong thư viện…"
          class="h-8 w-full pl-8 pr-3 rounded-sm bg-surface-2 border border-transparent text-sm text-text placeholder:text-text-subtle hover:bg-hover focus:border-accent focus:bg-surface-2 focus:outline-none transition-colors"
        />
      </div>
    </header>

    {#if filtered.length === 0}
      <EmptyState title={query ? 'Không tìm thấy' : 'Trống ở mục này'} hint={query ? 'Thử từ khoá khác.' : 'Chuyển sang mục khác hoặc thêm truyện.'} />
    {:else}
      <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3 sm:gap-4">
        {#each filtered as work (work.id)}
          <WorkCard work={{
            id: work.id,
            title: work.title,
            cover_url: work.cover_url,
            source: work.sources[0]?.source ?? null,
            nsfw: work.nsfw,
          }} />
        {/each}
      </div>
    {/if}

    <AddMangaModal open={addOpen} onClose={() => { addOpen = false; }} />
  </div>
{/if}

// web/src/routes/library.tsx
// /library — pinned works.
//
// A "library entry" is a Work with `in_library=true`. Browse-only works
// don't show up here; they live in /explore and the Recent rail.

import { useMemo, useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { Plus, Search } from 'lucide-react'

import { useLibraryWorks, useLibraryStatusCounts } from '@features/library/queries'
import { WorkCard } from '@features/library/WorkCard'
import { LibraryStatusTabs, type LibraryStatusOrAll } from '@features/library/LibraryStatusTabs'
import { AddMangaModal } from '@features/library/AddMangaModal'
import { EmptyState } from '@shared/ui/EmptyState'
import { Spinner, input as inputCls } from '@shared/ui/primitives'
import { Button } from '@shared/ui/Button'


function LibraryPage() {
  const lib = useLibraryWorks()
  const counts = useLibraryStatusCounts()
  const [status, setStatus] = useState<LibraryStatusOrAll>('all')
  const [query,  setQuery]  = useState('')
  const [addOpen, setAddOpen] = useState(false)

  const filtered = useMemo(() => {
    const items = lib.data ?? []
    const byStatus = status === 'all'
      ? items
      : items.filter(it => it.library_status === status)
    const q = query.trim().toLowerCase()
    if (!q) return byStatus
    return byStatus.filter(it => it.title.toLowerCase().includes(q))
  }, [lib.data, status, query])

  if (lib.isPending) {
    return (
      <div className="flex items-center justify-center py-16">
        <Spinner size={20} />
      </div>
    )
  }

  const items = lib.data ?? []
  if (items.length === 0) {
    return (
      <>
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
          <EmptyState
            title="Thư viện trống"
            hint="Tìm truyện hoặc dán URL để thêm vào."
            action={
              <Button variant="primary" size="md" onClick={() => setAddOpen(true)}>
                <Plus size={14} /> Thêm truyện
              </Button>
            }
          />
        </div>
        <AddMangaModal open={addOpen} onClose={() => setAddOpen(false)} />
      </>
    )
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-5">
      <header className="space-y-3">
        <div className="flex items-center justify-between gap-3">
          <div>
            <h1 className="text-lg font-semibold text-text">Thư viện</h1>
            <p className="text-xs text-text-muted">{items.length} truyện</p>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="secondary" size="sm" onClick={() => setAddOpen(true)}>
              <Plus size={14} /> Thêm
            </Button>
            <Link to="/explore">
              <Button variant="ghost" size="sm">Khám phá</Button>
            </Link>
          </div>
        </div>

        <LibraryStatusTabs value={status} onChange={setStatus} counts={counts} />

        <div className="relative max-w-xl">
          <Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-text-subtle" />
          <input
            type="search"
            placeholder="Tìm trong thư viện…"
            value={query}
            onChange={e => setQuery(e.target.value)}
            className={`${inputCls} pl-8`}
          />
        </div>
      </header>

      {filtered.length === 0 ? (
        <EmptyState
          title={query ? 'Không tìm thấy' : 'Trống ở mục này'}
          hint={query ? 'Thử từ khoá khác.' : 'Chuyển sang mục khác hoặc thêm truyện.'}
        />
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3 sm:gap-4">
          {filtered.map(it => (
            <WorkCard
              key={it.id}
              work={{
                id:        it.id,
                title:     it.title,
                cover_url: it.cover_url,
                source:    it.sources[0]?.source ?? null,
                nsfw:      it.nsfw,
              }}
            />
          ))}
        </div>
      )}

      <AddMangaModal open={addOpen} onClose={() => setAddOpen(false)} />
    </div>
  )
}

export const Route = createFileRoute('/library')({
  component: LibraryPage,
  staticData: { auth: 'required' },
})
