// web/src/features/work/components/WorkSources.tsx
// WorkSources — attached sources strip below the hero.
//
// Reads sources + primaryIdx from context. Detach action via
// useWorkActions(). Only the `onAttach` callback comes from the
// parent (it owns the modal state).

import { Plus } from 'lucide-react'

import { Cover } from '@shared/ui/Cover'
import { Spinner } from '@shared/ui/primitives'
import { Menu, type MenuItem } from '@shared/ui/Menu'
import { confirm } from '@shared/ui/Confirm'
import { toast } from '@shared/ui/Toaster'
import { cn } from '@shared/lib/cn'
import { useEnabledSources } from '@features/browse/sources'

import { useWorkIdentity } from '../contexts/WorkIdentityContext'
import { useWorkChapters } from '../contexts/WorkChaptersContext'
import { useWorkActions } from '../contexts/WorkActionsContext'
import type { WorkSource } from '../data/types'


interface Props {
  onAttach: () => void
}


export function WorkSources({ onAttach }: Props) {
  const { work, primaryIdx } = useWorkIdentity()
  const { loading } = useWorkChapters()

  const ordered = work.sources.length > 1 && primaryIdx > 0
    ? [work.sources[primaryIdx]!, ...work.sources.filter((_, i) => i !== primaryIdx)]
    : work.sources

  return (
    <section className="px-4 sm:px-6 pt-1 pb-3">
      <div className="flex items-center gap-2 mb-2">
        <h2 className="text-xs uppercase tracking-wider text-text-subtle font-medium">
          Nguồn
        </h2>
        <span className="text-xs text-text-subtle tabular-nums">{work.sources.length}</span>
        {loading && <Spinner size={12} />}
      </div>

      <div className="flex flex-wrap gap-2">
        {ordered.map((s, i) => (
          <SourceCard
            key={`${s.source}:${s.upstream_ref}`}
            source={s}
            isPrimary={i === 0 && work.sources.length > 1 && primaryIdx >= 0}
          />
        ))}
        <AttachCard onAttach={onAttach} />
      </div>
    </section>
  )
}


const CARD = 'flex-1 basis-[200px] min-w-[180px] max-w-[320px]'


function SourceCard({ source, isPrimary }: {
  source:     WorkSource
  isPrimary?: boolean
}) {
  const installed   = useEnabledSources()
  const { detachSource } = useWorkActions()
  const manifest    = installed.find(s => s.manifest.id === source.source)?.manifest
  const sourceLabel = manifest?.name ?? source.source
  const langLabel   = (source.languages[0] ?? '').toUpperCase()

  async function handleDetach() {
    const ok = await confirm({
      title:       `Gỡ "${sourceLabel}"?`,
      description: 'Có thể thêm lại sau.',
      confirmText: 'Gỡ',
      tone:        'danger',
    })
    if (!ok) return
    try {
      detachSource(source.source, source.upstream_ref)
      toast.success(`Đã gỡ "${sourceLabel}".`)
    } catch (e) { toast.error((e as Error).message) }
  }

  const menuItems: MenuItem[] = [
    { key: 'detach', label: 'Gỡ nguồn', danger: true, onSelect: handleDetach },
  ]

  return (
    <div className={cn(
      CARD,
      'flex items-center gap-2 h-11 pl-2 pr-1 rounded-sm bg-surface-2',
      isPrimary && 'border-l-2 border-accent',
    )}>
      <div className="w-6 h-8 shrink-0 rounded-xs overflow-hidden">
        <Cover src={source.cover_url} title={source.title} className="w-full h-full" fontSize="text-[10px]" />
      </div>
      <div className="flex-1 min-w-0 text-sm truncate">
        {langLabel && <span className="text-xs text-text-subtle font-medium mr-1.5">{langLabel}</span>}
        <span className="text-text">{sourceLabel}</span>
        {isPrimary && <span className="ml-1.5 text-xs text-accent">Chính</span>}
      </div>
      <Menu
        trigger={<span className="text-sm tracking-[2px] leading-none">···</span>}
        align="end"
        items={menuItems}
      />
    </div>
  )
}


function AttachCard({ onAttach }: { onAttach: () => void }) {
  return (
    <button
      type="button"
      onClick={onAttach}
      className={cn(
        CARD,
        'flex items-center gap-2 h-11 px-2 rounded-sm',
        'text-sm text-text-muted bg-transparent hover:bg-surface-2 hover:text-text',
        'border border-dashed border-border-soft transition-colors cursor-pointer text-left',
      )}
    >
      <span className="w-6 h-8 shrink-0 rounded-xs flex items-center justify-center bg-surface-2">
        <Plus size={12} className="text-text-subtle" />
      </span>
      Thêm nguồn
    </button>
  )
}

// web-svelte/src/lib/work/WorkSources.svelte
<script lang="ts">
  import { Plus, X } from 'lucide-svelte';
  import { cn } from '$lib/cn';
  import type { Work } from '$lib/db';
  import type { InstalledSource } from '$lib/source/types';
  import Cover from '$lib/ui/Cover.svelte';

  let {
    work,
    sourceMap = new Map<string, InstalledSource | null>(),
    detailLoading = false,
    detailFailures = 0,
    detachPending = false,
    detachError = '',
    onDetach = (_source: string, _upstreamRef: string) => {},
    onAttach = () => {},
  }: {
    work: Work;
    sourceMap: Map<string, InstalledSource | null>;
    detailLoading: boolean;
    detailFailures: number;
    detachPending?: boolean;
    detachError?: string;
    onDetach: (source: string, upstreamRef: string) => void;
    onAttach: () => void;
  } = $props();

  function sourceLabel(id: string): string {
    return sourceMap.get(id)?.manifest.name ?? id;
  }

  function sourceImageHeaders(id: string): Record<string, string> | undefined {
    return sourceMap.get(id)?.manifest.imageHeaders;
  }
</script>

<section class="pt-1 pb-3">
  <div class="flex items-center gap-2 mb-2">
    <h2 class="text-xs uppercase tracking-wider text-text-subtle font-medium">Nguồn</h2>
    <span class="text-xs text-text-subtle tabular-nums">{work.sources.length}</span>
    {#if detailLoading}<span class="ts-spinner-circle size-3 text-text-subtle" aria-label="Đang tải"></span>{/if}
    {#if detailFailures > 0}<span class="text-xs text-warning-text">{detailFailures} nguồn lỗi</span>{/if}
  </div>
  <div class="flex flex-wrap gap-2">
    {#each work.sources as source, i (`${source.source}:${source.upstream_ref}`)}
      <div class={cn(
        'flex-1 basis-[200px] min-w-[180px] max-w-[320px] flex items-center gap-2 h-11 pl-2 pr-1 rounded-sm bg-surface-2 group/src',
        i === 0 && work.sources.length > 1 && 'border-l-2 border-accent',
      )}>
        <div class="w-6 h-8 shrink-0 rounded-xs overflow-hidden">
          <Cover src={source.cover_url} headers={sourceImageHeaders(source.source)} title={source.title} class="w-full h-full" fontSize="text-[10px]" />
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-sm text-text truncate leading-tight">{source.title}</p>
          <p class="text-xs text-text-subtle truncate">
            {sourceLabel(source.source)}{#if i === 0 && work.sources.length > 1}<span class="ml-1 text-accent">Chính</span>{/if}
          </p>
        </div>
        {#if work.sources.length > 1}
          <button type="button"
            onclick={() => { if (confirm(`Gỡ nguồn "${sourceLabel(source.source)}"?`)) onDetach(source.source, source.upstream_ref); }}
            disabled={detachPending}
            class="shrink-0 size-6 rounded-sm flex items-center justify-center text-text-subtle hover:text-error-text hover:bg-error-bg opacity-0 group-hover/src:opacity-100 transition-opacity cursor-pointer disabled:opacity-40 disabled:cursor-wait"
            aria-label="Gỡ nguồn">
            <X size={12} />
          </button>
        {/if}
      </div>
    {/each}
    <button type="button" onclick={onAttach}
      class="flex-1 basis-[200px] min-w-[180px] max-w-[320px] flex items-center gap-2 h-11 px-2 rounded-sm text-sm text-text-muted bg-transparent hover:bg-surface-2 hover:text-text border border-dashed border-border-soft transition-colors cursor-pointer text-left">
      <span class="w-6 h-8 shrink-0 rounded-xs flex items-center justify-center bg-surface-2"><Plus size={12} class="text-text-subtle" /></span>
      Thêm nguồn
    </button>
  </div>
  {#if detachError}<p class="text-xs text-error-text mt-1">{detachError}</p>{/if}
</section>
